### ISSUE TITLE
Message Echo?

### ISSUE THREAD

**Issue by drewww** [candy-chat/candy#144]
This may well be an ejabberd issue, but I thought I'd mention it here in case anyone had insights...

I'm seeing an issue where occasionally I will send an outgoing chat message appear once in my chat list when I send it, and then appear against a minute later. It happens only for the client sending the message. After some testing, it seems only to happen in situations where there are no intervening messages; during an actual back and forth it never seems to happen. 

Not sure if this is a bug in candy or in ejabberd. I'll try to do some more debugging when the room quiets down to see what the xmpp messages look like and see if another message is coming from the server or not. Will update with more data soon!

**Comment by hadrienk** [comment]
I got the same case with Candy -> nginx -> nginx -> openfire.

The connection gets dropped after a 504 timeout because two similar messages are sent with the same rid. I don't know if this should be failing or not (openfire bug?) but reducing the timeout to a very low value in nginx seems to do the trick for me.
```
location /http-bind/ {
        proxy_set_header Host $host;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_buffering off;
        tcp_nodelay on;

        proxy_read_timeout 10s;
        proxy_send_timeout 10s;

        proxy_pass  http://localhost:7070/http-bind/;
    }
```

I will let things connected for the night and update.

**Comment by hadrienk** [comment]
Well, I stayed connected 10 hours wheras I couldn't stay more that a couple of minutes before this change so this had a clear impact.
